const types = {
  CREATE_NEW_GAME: 'CREATE_NEW_GAME',
  UPDATE_CURRENT_USER: 'UPDATE_CURRENT_USER',
  UPDATE_USER_ANSWER: 'UPDATE_USER_ANSWER',
  UPDATE_ANSWER_IS_CORRECT: 'UPDATE_ANSWER_IS_CORRECT',
  GO_TO_THE_NEXT_QUESTION: 'GO_TO_THE_NEXT_QUESTION'
};

export default types;
